project_id = "dxwowuztnmjewkncptji"

[functions.vici-sync]
verify_jwt = false

[functions.transcribe-pending]
verify_jwt = true

[functions.transcribe-background]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.get-signed-url]
verify_jwt = true

[functions.proxy-audio]
verify_jwt = true

[functions.transcribe-vicidial]
verify_jwt = true
